use supply_chain;
-- level 1
-- Q1 READ THE DATA FROM THE TABLES
SELECT * from supplier;
SELECT * FROM product;
SELECT * FROM orderitem;
SELECT * FROM orders;
SELECT * FROM customer;
-- Q2 FIND THE COUNTRY WISE COUNT OF CUSTOMERS
select country, count(id) AS count_cust
from customer
group by country
order by count_cust DESC;

-- Q3 display the products that are not discontinued
select * from product
where isdiscontinued = '1';

-- Q4 list of companies along with product name that they are supplying
select s.companyname,p.productname
from supplier s
join product p on s.id= p.supplierid;

-- Q5 display customer who stays in mexico
select * from customer
where country = 'Mexico';

-- Q6 costiest item that is ordered by he customer
select c.id as customer_id,p.productname,p.unitprice
from customer c
join orders o on c.id = o.customerid
join orderitem oi on o.id = oi.orderid
join product p on p.id = oi.productid
where (c.id, p.unitprice) in (
    SELECT c.id, MAX(p.unitprice) 
    FROM product p
    JOIN orderitem oi ON oi.productid = p.id
    JOIN orders o ON o.id = oi.orderid
    JOIN customer c ON o.customerid = c.id
    GROUP BY c.id
);
 -- Q7 Display supplieer ID who owns the highest number of products
 with max_p as (
	 select s.id, COUNT(p.id) as cnt_prod
     from supplier s
     join product p on p.supplierid = s.id
     group by s.id
)
select * from max_p
where cnt_prod IN (select max(cnt_prod) from 
max_p);

-- Q8 Display month wise and year wise counts of the orders placed
select year(orderdate) as year , month(orderdate) 
as month , count(id) as order_count
from orders
group by year(orderdate), month(orderdate)
order by year asc, month asc;

-- Q9 which country has the maximum number of suppliers

WITH max_c AS (
    SELECT country, COUNT(id) OVER(PARTITION BY country) AS count
    FROM supplier
)
SELECT DISTINCT * FROM max_c 
WHERE count IN (SELECT MAX(count) FROM max_c);

-- Q10 which customers did not place any orders
select * from customer
where id not in (select customerid from orders);

-- SECTION B :LEVEL 2 (Intermediate queries)
-- Q1 Arrange the product ID and name based on the high demand by the customer
select p.id as product_id, p.productname,sum(oi.quantity)as total_quantity
from orderitem oi
join product p on p.id = oi.productid
group by p.id, p.productname
order by total_quantity desc;

-- Q2 Display the total number of orders delivered every year
select year(orderdate) as year, count(id) as
total_orders
from orders
group by year(orderdate);

-- Q3 calculate year wise total revenue
select year(orderdate) as year, sum(totalamount)
as total_revenue
from orders
group by year(orderdate);

-- Q4 Display the customer details whose order amount is maximum including his past orders
select c.*, sum(totalamount) as
total_order_amount
from customer c
join orders o on o.customerid = c.id
group by c.id
order by sum(totalamount) desc
limit 1;

-- Q5 Display the total amount ordered by each customer from high to low
SELECT c.*, SUM(totalamount) AS total_order_amount 
FROM customer c
JOIN orders o ON o.customerid = c.id
group by c.id
ORDER BY SUM(totalamount) DESC;

-- Q6 List the current and previous order dates for each customer

select c.id AS customerid, c.firstname, o.orderdate
FROM customer c 
JOIN orders o ON o.customerid = c.id
ORDER BY customerid, orderdate;

-- Q7Find out the top 3 suppliers in terms of revenue generated by their products
SELECT s.id as supplierid,s.contactname,
sum(quantity*oi.unitprice)as totalrevenue
from supplier s
join product p on s.id=p.supplierid
join orderitem oi on oi.productid = p.id
join orders o on o.id = oi.orderid
group by s.id, s.contactname
order by totalrevenue desc
limit 3;

-- Q8 Display the latest order date of all the customers with customer details
select c.*,MAX(orderdate) as latest_order_date
from customer c
join orders o on o.customerid = c.id
group by c.id;

-- Q9 Display the product name and supplier name for each order

select oi.orderid, p.productname,s.contactname
as suppliername
from supplier s
join product p on p.supplierid= s.id
join orderitem oi on oi.productid= p.id
join orders o on o.id = oi.orderid;

-- SECTION C : Level 3 (Advanced Queries)
-- Q1  Fetch the customer details who ordered more than 10 products in a single order
with product_ordered as (
     select distinct c.*,count(o.id) over
     (partition by c.id) as count
     from customer c
     join orders o on o.customerid = c.id
)
select * from product_ordered
where count > 10
order by count desc;

-- 2. Display all the product details with the ordered quantity size as 1

SELECT p.* 
FROM product p 
JOIN orderitem oi ON oi.productid = p.id 
WHERE quantity = 1;


-- 3. Display the companies that supply products whose cost is above 100

SELECT DISTINCT s.* 
FROM supplier s 
JOIN product p ON p.SupplierId = s.id
JOIN orderitem oi ON oi.productid = p.id 
WHERE oi.unitprice > 100;


-- 4. Display the customer list who belongs to the same city and country arranged country-wise

SELECT DISTINCT c1.id, c1.firstname, c2.FirstName, c1.city, c1.country
FROM customer c1 
JOIN customer c2 ON (c1.city, c1.country) = (c2.city, c2.country)
WHERE c1.id <> c2.id
ORDER BY c1.country;

-- SECTION D: Level 4 (expert queries)
-- Q1  Calculate the total amount saved in each order and rank by savings
SELECT oi.orderid, SUM((p.unitprice - oi.unitprice) * oi.quantity) AS total_amount_saved
FROM product p 
JOIN orderitem oi ON p.id = oi.productid
GROUP BY oi.orderid 
ORDER BY total_amount_saved DESC;

-- Q2 Market Research for Mr. Kavin
-- A HIGH DEMAND PRODUCTS
SELECT p.productname, SUM(oi.quantity) AS total_demand
FROM product p
JOIN orderitem oi ON p.id = oi.productid
GROUP BY p.productname
ORDER BY total_demand DESC;

-- B Competitors for high-demand products
SELECT DISTINCT s.contactname, p.productname
FROM orderitem oi 
JOIN product p ON p.id = oi.productid
JOIN supplier s ON p.supplierid = s.id;

 
